### ISSUE TITLE
ReadME.

### ISSUE THREAD

**Issue by julisNew** [AchrafFriaa/MID#2]
**Prerequisites**

Can you reproduce the problem reliably? Yes

Did you check current release notes for known issues? Yes

If this is not the latest release, have you checked newer releases?  Yes

in README.mk file said,
      Dependencies: 
      pip install {lib}
      numpy
      scipy version 1.3+ (subpackge optimize the differential_evolution code)
      pyserial
      magpylib v2.2.0+ (included in the folder)

but actually, there is no magpylib==2.2.0 and the newest version is not compatible with repo

for  magpylib==2.2.0:
      ERROR: Could not find a version that satisfies the requirement magpylib==2.5.300 (from versions: 1.0.2b0, 1.1.0b0, 1.1.1b0, 1.2.0b0, 1.2.1b0, 2.0.0b0, 2.1.0b0, 2.3.0b0, 3.0.2, 3.0.4, 3.0.5, 4.0.0b2, 4.0.0rc0, 4.0.0rc1, 4.0.0rc2, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.3.0rc1, 4.3.0)
      ERROR: No matching distribution found for magpylib==2.5.300
      WARNING: You are using pip version 21.2.3; however, version 23.2.1 is available.
      You should consider upgrading via the 'C:\Projects\magnetic-3d-mini-controller\miniCtl_py\Scripts\python.exe -m pip install --upgrade pip' command.

for  magpylib==3.0.2 or 4.3.0:
    AttributeError: module 'magpylib' has no attribute 'vector'

And I've tried it's working with magpylib==2.3.0b0
